// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCszT6TwQdt6JIWRzD5MqoaNrRmUSTgx6s',
    appId: '1:829753064945:web:9925488000788122985850',
    messagingSenderId: '829753064945',
    projectId: 'prm-cart',
    authDomain: 'prm-cart.firebaseapp.com',
    storageBucket: 'prm-cart.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB3nYGxCXWwqn1FmjI7dvc0K566oadueU',
    appId: '1:829753064945:android:a8cdeb76110d8ce8985850',
    messagingSenderId: '829753064945',
    projectId: 'prm-cart',
    storageBucket: 'prm-cart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBrKGQqva3E81smFIudNZiBxQNXNEWk0g',
    appId: '1:829753064945:ios:b62c9decab17711e985850',
    messagingSenderId: '829753064945',
    projectId: 'prm-cart',
    storageBucket: 'prm-cart.appspot.com',
    iosBundleId: 'com.example.prmCart',
  );
}
